trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment: 
   name: web
   resourceType: VirtualMachine
  strategy:
     runOnce:
        deploy:   
          steps:
            - task: NodeTool@0
              inputs:
                versionSpec: '12.x'
              displayName: 'Install Node.js'
            - script: |
                npm install
                node index.js
              displayName: 'npm install and run'
